name: myvazi
description: "Dealing in all types of clothing."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'  # sdk: '>=3.2.0-210.2.beta <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.5.0
  meta: ^1.10.0
  web: ^0.2.1-beta
  http: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  intl_phone_number_input: ^0.7.3+1
  provider: ^6.0.5
  permission_handler: any
  image_picker: ^0.7.3
  flutter_plugin_android_lifecycle: 2.0.0
  image: ^4.1.3
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  carousel_slider:
#  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
     - assets/data/